### ISSUE TITLE
Encode binaries to YAML using the `!!binary` tag

### ISSUE THREAD

**Issue by k1LoW** [goccy/go-yaml#558]
**Is your feature request related to a problem? Please describe.**

I need a way to encode binary to YAML using the `!!binary` tag. If it exists, I would like to know.

**Describe the solution you'd like**

I couldn't find a way to encode binaries with the `!!binary` tag when encoding to YAML.

**Describe alternatives you've considered**

Once converted to AST, then replace nodes (however, it is not a method I would like to choose). 

**Additional context**

Not sure if the gopkg.in/yaml.v* method is better, but I will share that the behavior is different.

https://go.dev/play/p/Iaux074EOuB

**Comment by goccy** [comment]
@k1LoW Thank you for your reporting!

If we decide to support this, one approach could be encoding `[]byte` as `!!binary` with base64 encoding. However, since this would introduce breaking changes, I’d like to consider it carefully. 

As a workaround, you can use `RegisterCustomMarshaler`, which allows you to modify the encoding method for any type. Here’s a sample code snippet

https://go.dev/play/p/ViPKVp4zlav

**Comment by k1LoW** [comment]
Nice workaround, thank you!
This is good enough for me!
